language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.1
  - 2.3.3
bundler_args: --without production
before_install: gem install rainbow -v '2.2.1' # TMP
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
env:
  - SECRET_KEY_BASE="abc123_test" DEVISE_SECRET_KEY="abc123_test"
