language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.0
  - 2.3.1
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
env:
  - SECRET_KEY_BASE="abc123_test" DEVISE_SECRET_KEY="abc123_test"
