# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

APP_EMAIL_SENDER: "you.email@domain.com"
FACEBOOK_KEY: xxx
FACEBOOK_SECRET: xxx
TWITTER_KEY: xxx
TWITTER_SECRET: xxx

development:
  COOKIE_STORE_KEY: "abc123_dev"
  DB_HOST: localhost
  DB_DATABASE: fspp_development
  DB_SCHEMA: public
  DB_USERNAME: xxx
  DB_PASSWORD: xxx
  DB_PORT: "5432"
  DEVISE_SECRET_KEY: "abc123_dev"
  SECRET_KEY_BASE: "abc123_dev"

test:
  COOKIE_STORE_KEY: "abc123_test"
  DB_HOST: localhost
  DB_DATABASE: fspp_test
  DB_SCHEMA: public
  DB_USERNAME: xxx
  DB_PASSWORD: xxx
  DB_PORT: "5432"
  DEVISE_SECRET_KEY: "abc123_test"
  SECRET_KEY_BASE: "abc123_test"

production:
  APP_EMAIL_SENDER: "you.email@domain.com"
  DEVISE_SECRET_KEY: abc123_prod
  DB_HOST: xxx
  DB_DATABASE: xxx
  DB_SCHEMA: xxx
  DB_USERNAME: xxx
  DB_PASSWORD: xxx
  DB_PORT: xxx
  DEVISE_SECRET_KEY: abc123_prod
  FACEBOOK_KEY: KEY
  FACEBOOK_SECRET: SECRET
  HOST: "example.com"
  REPLY_EMAIL_ADDRESS: "no-reply@example.com"
  SECRET_KEY_BASE: abc123_prod
  TWITTER_KEY: KEY
  TWITTER_SECRET: SECRET
